name: Test Execution

on:
  schedule:
    # 4:30 AM UTC is 10:00 AM IST
    - cron: '30 4 * * 2,6'
  push:
    branches: [ main , master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # Configure Gradle environment and automatic caching
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Execute your tests using standard run step
      - name: Run Gradle tests
        run: ./gradlew test --info
        # working-directory: ./your-subfolder-name # Uncomment if project is in a subfolder

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test/
